---
# tasks file for master
- name: Init Docker Swarm Master
  become: yes
  command: docker swarm init --advertise-addr 192.168.56.11
  
- name: Get Workers Token
  become: yes
  command: docker swarm join-token worker -q
  register: command_output

- set_fact:
    work_token: "{{ command_output.stdout }}"
    cachable: yes

- debug: 
    msg: "{{work_token}}"